import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ThemeToggle } from "@/components/theme-toggle";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background text-foreground antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <header className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 py-4">
            <Link href="/" className="text-lg font-bold">Khane</Link>
            <nav className="space-x-6 hidden md:block">
              <a href="/work-with-me">Work With Me</a>
              <a href="/portfolio">Portfolio</a>
              <a href="/blog">Blog</a>
              <a href="/about">About</a>
              <a href="/contact" className="font-semibold">Start a Project</a>
            </nav>
            <ThemeToggle />
          </header>
          <main className="pt-24">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
